# Generated by Django 5.1.4 on 2026-01-26 16:32

from django.db import migrations

def create_initial_configs(apps, schema_editor):
    SystemConfig = apps.get_model('adminpanel', 'SystemConfig')
    
    configs = [
        {
            'key': 'option_price_sync_start_date',
            'value': '2024-01-01',
            'description': 'Start date for option data sync (indices only)',
            'is_public': False
        },
        {
            'key': 'option_strike_price_range_pct',
            'value': '5.0',
            'description': 'Percentage to filter strikes around spot price',
            'is_public': False
        }
    ]
    
    for config_data in configs:
        if not SystemConfig.objects.filter(key=config_data['key']).exists():
            SystemConfig.objects.create(**config_data)

class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_configs),
    ]
