# Generated by Django 5.0 on 2025-12-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
    ]
