# Generated by Django 5.2.3 on 2025-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_add_stocks_sectors_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='can_manage_stocks',
            field=models.BooleanField(default=False),
        ),
    ]
