# Generated by Django 5.0 on 2025-12-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal Sync'), ('hard', 'Hard Sync')], default='normal', help_text='Normal sync uses last_synced_at, Hard sync uses specific date range', max_length=20),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('sector', 'Sector'), ('option', 'Option')], max_length=20),
        ),
    ]
