# Generated by Django 5.1.4 on 2025-12-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketStatus',
        ),
    ]
