# Generated by Django 6.0.2 on 2026-02-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(db_index=True, help_text='NIFTY, BANKNIFTY, etc.', max_length=50)),
                ('expiry_date', models.DateField(db_index=True, help_text='Contract expiry date')),
                ('strike_price', models.DecimalField(decimal_places=2, help_text='Strike price', max_digits=10)),
                ('option_type', models.CharField(choices=[('CE', 'Call Option'), ('PE', 'Put Option')], help_text='CE (Call) or PE (Put)', max_length=2)),
                ('date', models.DateField(db_index=True, help_text='Trading date for this record')),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, help_text='Opening price', max_digits=15, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, help_text='High price', max_digits=15, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, help_text='Low price', max_digits=15, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, help_text='Closing price', max_digits=15, null=True)),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, help_text='Last traded price', max_digits=15, null=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=2, help_text='Previous day close', max_digits=15, null=True)),
                ('settle_price', models.DecimalField(blank=True, decimal_places=2, help_text='Settlement price', max_digits=15, null=True)),
                ('volume', models.BigIntegerField(blank=True, help_text='Total traded quantity', null=True)),
                ('traded_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total traded value in lakhs', max_digits=20, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, help_text='Open interest', null=True)),
                ('change_in_oi', models.BigIntegerField(blank=True, help_text='Change in open interest', null=True)),
                ('underlying_value', models.DecimalField(blank=True, decimal_places=2, help_text='Spot price of underlying at close', max_digits=15, null=True)),
                ('calculated_premium', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated premium value', max_digits=15, null=True)),
                ('market_lot', models.IntegerField(default=25, help_text='Market lot size')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Additional data from NSE or calculated fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_data', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Option Daily Data',
                'verbose_name_plural': 'Option Daily Data',
                'db_table': 'option_daily_data',
                'ordering': ['-date', 'strike_price'],
                'indexes': [models.Index(fields=['stock', 'expiry_date', 'date'], name='option_dail_stock_i_da4d7e_idx'), models.Index(fields=['underlying_symbol', 'expiry_date', 'date'], name='option_dail_underly_4d1494_idx'), models.Index(fields=['underlying_symbol', 'date'], name='option_dail_underly_879ea7_idx'), models.Index(fields=['date'], name='option_dail_date_219dd3_idx'), models.Index(fields=['expiry_date'], name='option_dail_expiry__f520e9_idx')],
                'unique_together': {('underlying_symbol', 'expiry_date', 'strike_price', 'option_type', 'date')},
            },
        ),
    ]
