# Generated by Django 5.0 on 2025-12-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_type', models.CharField(choices=[('stock', 'Stock'), ('sector', 'Sector')], help_text='Stock or Sector', max_length=10)),
                ('underlying_symbol', models.CharField(db_index=True, help_text='e.g. RELIANCE, NIFTY50', max_length=50)),
                ('expiry_date', models.DateField(db_index=True, help_text='Contract expiry date')),
                ('option_type', models.CharField(choices=[('CE', 'Call Option (CE)'), ('PE', 'Put Option (PE)')], help_text='CE or PE', max_length=3)),
                ('option_strike', models.DecimalField(decimal_places=2, help_text='Strike price', max_digits=10)),
                ('candles_json', models.JSONField(default=dict, help_text='5-min bars: {"09:15": {open, high, low, close, volume}, ...}')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option 5-Minute Data',
                'verbose_name_plural': 'Options 5-Minute Data',
                'db_table': 'options_5min',
                'ordering': ['-expiry_date', 'option_strike'],
                'indexes': [models.Index(fields=['underlying_symbol', 'expiry_date'], name='options_5mi_underly_293909_idx'), models.Index(fields=['expiry_date'], name='options_5mi_expiry__96184b_idx')],
                'unique_together': {('underlying_symbol', 'expiry_date', 'option_type', 'option_strike')},
            },
        ),
    ]
