# Generated by Django 5.1.4 on 2026-01-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option5Min',
        ),
    ]
