# Generated by Django 5.1.4 on 2026-01-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_initial'),
        ('stocks', '0004_stock_option_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiondailydata',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_data', to='stocks.stock'),
        ),
        migrations.AddIndex(
            model_name='optiondailydata',
            index=models.Index(fields=['stock', 'expiry_date', 'date'], name='option_dail_stock_i_da4d7e_idx'),
        ),
    ]
