# Generated by Django 5.1.4 on 2026-01-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_start_date',
        ),
    ]
