# Generated by Django 5.1.4 on 2025-12-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectorPriceDaily',
        ),
    ]
