# Generated by Django 5.2.3 on 2025-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
