# Generated by Django 5.2.3 on 2025-12-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_sector_last_synced_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='enum',
            new_name='symbol',
        ),
    ]
