# Generated by Django 5.1.4 on 2026-01-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_delete_sectorpricedaily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='last_synced_at',
        ),
    ]
