# Generated by Django 6.0.2 on 2026-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('strategy_custom_script', models.TextField(blank=True, help_text='Custom script (not persisted)')),
                ('selection_mode', models.CharField(choices=[('stock', 'Specific Stocks'), ('sector', 'Sector'), ('category', 'Category'), ('watchlist', 'My Watchlist')], default='stock', max_length=20)),
                ('selection_config', models.JSONField(blank=True, default=dict, help_text='IDs of selected stocks/sectors/categories')),
                ('criteria_type', models.CharField(choices=[('direction', 'Direction Only (UP/DOWN)'), ('magnitude', 'Direction + Magnitude (50%)')], default='direction', max_length=20)),
                ('magnitude_threshold', models.IntegerField(default=50, help_text='Percentage verification threshold (0-100)')),
                ('trade_strategy', models.CharField(blank=True, choices=[('re_entry', 'Active Trading (Re-Entry at Signal)'), ('buy_hold', 'Buy & Hold (First Signal to End)')], max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_wallet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_signals', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('list_of_trades_json', models.JSONField(blank=True, default=list)),
                ('equity_curve_json', models.JSONField(blank=True, default=list)),
                ('instrument_type', models.CharField(default='stock', max_length=10)),
                ('instrument_identifier', models.CharField(default='', max_length=100)),
                ('final_wallet_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_trades', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('time_taken', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backtest Run',
                'verbose_name_plural': 'Backtest Runs',
                'db_table': 'backtest_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionBacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('underlying_symbol', models.CharField(help_text='Symbol for option trading (Index or Stock)', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lot_size', models.IntegerField(default=50, help_text='Lot size/quantity per trade')),
                ('snapshot_name', models.CharField(blank=True, max_length=200, null=True)),
                ('snapshot_description', models.TextField(blank=True, null=True)),
                ('snapshot_config', models.JSONField(blank=True, help_text='Strategy logic snapshot at the time of run', null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0, help_text='Trades with positive PnL')),
                ('loss_count', models.IntegerField(default=0, help_text='Trades with negative PnL')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, help_text='Total PnL in currency', max_digits=15)),
                ('results_summary_json', models.JSONField(blank=True, default=dict, help_text='Summary stats like max drawdown, avg PnL per trade, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('time_taken', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option Backtest Run',
                'verbose_name_plural': 'Option Backtest Runs',
                'db_table': 'option_backtest_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(help_text='Index symbol (NIFTY, BANKNIFTY, etc.)', max_length=20)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('expiry_date', models.DateField(help_text='Option expiry date')),
                ('legs_json', models.JSONField(default=list, help_text='Array of legs with strike, type (CE/PE), action (BUY/SELL), entry/exit prices')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option Trade',
                'verbose_name_plural': 'Option Trades',
                'db_table': 'option_trades',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('stock', 'Stock'), ('sector', 'Sector'), ('option', 'Option')], default='stock', help_text='Type of instrument', max_length=10)),
                ('instrument_identifier', models.CharField(default='', help_text='Stock enum, sector enum, or option contract identifier', max_length=100)),
                ('stock_enum', models.CharField(blank=True, max_length=50)),
                ('buy_date', models.DateField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField()),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('strategy_id', models.CharField(blank=True, max_length=100)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['-created_at'],
            },
        ),
    ]
