# Generated by Django 5.1.4 on 2025-12-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('strategy_custom_script', models.TextField(blank=True, help_text='Custom script (not persisted)')),
                ('instrument_type', models.CharField(choices=[('stock', 'Stock'), ('sector', 'Sector'), ('option', 'Option')], default='stock', help_text='Type of instrument being backtested', max_length=10)),
                ('instrument_identifier', models.CharField(default='', help_text='Stock enum, sector enum, or option contract identifier', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_wallet_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_wallet_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_trades', models.IntegerField(default=0)),
                ('list_of_trades_json', models.JSONField(blank=True, default=list)),
                ('equity_curve_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('time_taken', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backtest Run',
                'verbose_name_plural': 'Backtest Runs',
                'db_table': 'backtest_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('stock', 'Stock'), ('sector', 'Sector'), ('option', 'Option')], default='stock', help_text='Type of instrument', max_length=10)),
                ('instrument_identifier', models.CharField(default='', help_text='Stock enum, sector enum, or option contract identifier', max_length=100)),
                ('stock_enum', models.CharField(blank=True, max_length=50)),
                ('buy_date', models.DateField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField()),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('strategy_id', models.CharField(blank=True, max_length=100)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['-created_at'],
            },
        ),
    ]
