# Generated by Django 5.1.4 on 2025-12-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtests', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_predefined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategypredefined'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_rule_based',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyrulebased'),
        ),
    ]
