# Generated by Django 6.0.2 on 2026-02-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtests', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_predefined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategymaster'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_rule_based',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategyrulebased'),
        ),
    ]
