# Generated by Django 6.0.2 on 2026-02-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtests', '0002_initial'),
        ('sectors', '0001_initial'),
        ('stocks', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optionbacktestrun',
            name='strategy',
            field=models.ForeignKey(help_text='Option Strategy to backtest', on_delete=django.db.models.deletion.CASCADE, to='strategies.optionstrategy'),
        ),
        migrations.AddField(
            model_name='optionbacktestrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_backtest_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optiontrade',
            name='backtest_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.optionbacktestrun'),
        ),
        migrations.AddField(
            model_name='optiontrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='backtest_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.backtestrun'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='optiontrade',
            index=models.Index(fields=['backtest_run', 'entry_date'], name='option_trad_backtes_bf39a6_idx'),
        ),
        migrations.AddIndex(
            model_name='optiontrade',
            index=models.Index(fields=['underlying_symbol', 'entry_date'], name='option_trad_underly_787b30_idx'),
        ),
    ]
