# Generated by Django 5.0 on 2025-12-05 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_initial'),
        ('sectors', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='instrument_identifier',
            field=models.CharField(default='', help_text='Stock enum, sector enum, or option contract identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='instrument_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('sector', 'Sector'), ('option', 'Option')], default='stock', help_text='Type of instrument being backtested', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='instrument_identifier',
            field=models.CharField(default='', help_text='Stock enum, sector enum, or option contract identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='instrument_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('sector', 'Sector'), ('option', 'Option')], default='stock', help_text='Type of instrument', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='sectors.sector'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock_enum',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
