# Generated by Django 5.1.4 on 2025-12-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_initial'),
        ('strategies', '0003_remove_strategypredefined_created_by_strategymaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='strategy_predefined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategymaster'),
        ),
    ]
