# Generated by Django 5.1.4 on 2025-12-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0004_alter_backtestrun_strategy_predefined'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='criteria_type',
            field=models.CharField(choices=[('direction', 'Direction Only (UP/DOWN)'), ('magnitude', 'Direction + Magnitude (50%)')], default='direction', max_length=20),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='loss_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='selection_config',
            field=models.JSONField(blank=True, default=dict, help_text='IDs of selected stocks/sectors/categories'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='selection_mode',
            field=models.CharField(choices=[('stock', 'Specific Stocks'), ('sector', 'Sector'), ('category', 'Category'), ('watchlist', 'My Watchlist')], default='stock', max_length=20),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='total_signals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='win_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='initial_wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='instrument_identifier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='instrument_type',
            field=models.CharField(default='stock', max_length=10),
        ),
    ]
