# Generated by Django 5.1.4 on 2025-12-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0005_backtestrun_criteria_type_backtestrun_loss_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='magnitude_threshold',
            field=models.IntegerField(default=50, help_text='Percentage verification threshold (0-100)'),
        ),
    ]
