# Generated by Django 5.1.4 on 2025-12-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0006_backtestrun_magnitude_threshold'),
        ('strategies', '0007_remove_strategymaster_logic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='strategy_predefined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategymaster'),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='strategy_rule_based',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategyrulebased'),
        ),
    ]
