# Generated by Django 5.1.4 on 2026-01-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0008_fix_fk_constraint_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='trade_strategy',
            field=models.CharField(blank=True, choices=[('re_entry', 'Active Trading (Re-Entry at Signal)'), ('buy_hold', 'Buy & Hold (First Signal to End)')], max_length=20, null=True),
        ),
    ]
