# Generated by Django 5.1.4 on 2026-02-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0009_backtestrun_trade_strategy'),
        ('strategies', '0014_optionstrategy_is_system_optionstrategy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_options',
            field=models.ForeignKey(blank=True, help_text='Linked Option Strategy', null=True, on_delete=django.db.models.deletion.CASCADE, to='strategies.optionstrategy'),
        ),
    ]
