# Generated by Django 5.1.4 on 2026-02-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0010_backtestrun_strategy_options'),
        ('strategies', '0014_optionstrategy_is_system_optionstrategy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionBacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('underlying_symbol', models.CharField(choices=[('NIFTY', 'NIFTY 50'), ('BANKNIFTY', 'BANK NIFTY'), ('FINNIFTY', 'NIFTY FINANCIAL'), ('MIDCPNIFTY', 'NIFTY MIDCAP SELECT')], help_text='Index for option trading', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0, help_text='Trades with positive PnL')),
                ('loss_count', models.IntegerField(default=0, help_text='Trades with negative PnL')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, help_text='Total PnL in currency', max_digits=15)),
                ('results_summary_json', models.JSONField(blank=True, default=dict, help_text='Summary stats like max drawdown, avg PnL per trade, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('time_taken', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(help_text='Option Strategy to backtest', on_delete=django.db.models.deletion.CASCADE, to='strategies.optionstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_backtest_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option Backtest Run',
                'verbose_name_plural': 'Option Backtest Runs',
                'db_table': 'option_backtest_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(help_text='Index symbol (NIFTY, BANKNIFTY, etc.)', max_length=20)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('expiry_date', models.DateField(help_text='Option expiry date')),
                ('legs_json', models.JSONField(default=list, help_text='Array of legs with strike, type (CE/PE), action (BUY/SELL), entry/exit prices')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.optionbacktestrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option Trade',
                'verbose_name_plural': 'Option Trades',
                'db_table': 'option_trades',
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['backtest_run', 'entry_date'], name='option_trad_backtes_bf39a6_idx'), models.Index(fields=['underlying_symbol', 'entry_date'], name='option_trad_underly_787b30_idx')],
            },
        ),
    ]
