# Generated by Django 5.1.4 on 2026-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0011_optionbacktestrun_optiontrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionbacktestrun',
            name='lot_size',
            field=models.IntegerField(default=50, help_text='Lot size/quantity per trade'),
        ),
    ]
