# Generated by Django 5.1.4 on 2026-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0012_optionbacktestrun_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionbacktestrun',
            name='underlying_symbol',
            field=models.CharField(help_text='Symbol for option trading (Index or Stock)', max_length=20),
        ),
    ]
