# Generated by Django 5.1.4 on 2026-02-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0013_alter_optionbacktestrun_underlying_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestrun',
            name='strategy_options',
        ),
    ]
