# Generated by Django 5.1.4 on 2026-02-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0014_remove_backtestrun_strategy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionbacktestrun',
            name='snapshot_config',
            field=models.JSONField(blank=True, help_text='Strategy logic snapshot at the time of run', null=True),
        ),
        migrations.AddField(
            model_name='optionbacktestrun',
            name='snapshot_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionbacktestrun',
            name='snapshot_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
