# Generated by Django 5.1.4 on 2025-12-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Category',
                'verbose_name_plural': 'Stock Categories',
                'db_table': 'stocks_category',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('exchange_suffix', models.CharField(default='NSE', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sectors', models.ManyToManyField(blank=True, related_name='stocks', to='sectors.sector')),
                ('categories', models.ManyToManyField(blank=True, related_name='stocks', to='stocks.stockcategory')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stocks_stock',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Stock5MinByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('candles_json', models.JSONField(help_text='Map of time -> OHLCV data')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_candles', to='stocks.stock')),
            ],
            options={
                'db_table': 'stock_5min_by_day',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockPriceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('iv', models.DecimalField(blank=True, decimal_places=4, help_text='Implied Volatility', max_digits=10, null=True)),
                ('timewise_json', models.JSONField(blank=True, help_text='Intraday timewise data if available', null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.stock')),
            ],
            options={
                'db_table': 'stock_price_daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='stock_price_stock_i_fc1c32_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
