# Generated by Django 5.1.4 on 2025-12-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_index',
            field=models.BooleanField(default=False, help_text='True if this is an Index/Sector, False if Equity'),
        ),
    ]
