# Generated by Django 5.0 on 2025-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='sectors.sector'),
        ),
    ]
