# Generated by Django 5.2.3 on 2025-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='enum',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='full_symbol',
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
