# Generated by Django 5.1.4 on 2026-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_is_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_option_enable',
            field=models.BooleanField(default=False, help_text='Enable option data sync for this index'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_option_sync',
            field=models.DateField(blank=True, help_text='Last date when option data was synced', null=True),
        ),
    ]
