# Generated by Django 5.1.4 on 2026-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_is_option_enable_stock_last_option_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='option_symbol',
            field=models.CharField(blank=True, default='', help_text='Symbol for NSE option API (e.g., NIFTY, BANKNIFTY)', max_length=50),
        ),
    ]
