# Generated by Django 5.1.4 on 2026-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_option_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lot_size',
            field=models.IntegerField(default=1, help_text='Default lot size for options trading'),
        ),
    ]
