# Generated by Django 5.1.4 on 2026-02-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lot_size',
            field=models.IntegerField(blank=True, help_text='Default lot size for options trading', null=True),
        ),
    ]
