# Generated by Django 5.1.4 on 2026-02-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_stock_lot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='lot_size',
        ),
    ]
