# Generated by Django 5.1.4 on 2026-02-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_remove_stock_lot_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock5MinByDay',
        ),
    ]
