# Generated by Django 6.0.2 on 2026-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='If True, visible to all users (Created by Admin)')),
                ('configuration', models.JSONField(help_text='Strategy logic (Legs, Entry, Exit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option Strategy',
                'verbose_name_plural': 'Option Strategies',
                'db_table': 'strategies_option',
            },
        ),
        migrations.CreateModel(
            name='StockFinderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategies', models.JSONField(help_text='List of strategy details used')),
                ('filters', models.JSONField(help_text='Filters applied (Sector, Category, Date, Direction)')),
                ('results', models.JSONField(help_text='List of stocks found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Finder History',
                'verbose_name_plural': 'Stock Finder Histories',
                'db_table': 'stock_finder_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the strategy (e.g., DAILY_CLOSE_MOMENTUM)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Master',
                'verbose_name_plural': 'Strategy Masters',
                'db_table': 'strategies_master',
            },
        ),
        migrations.CreateModel(
            name='StrategyRuleBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rules_json', models.JSONField(help_text='Strategy rules in JSON format')),
                ('is_public', models.BooleanField(default=False, help_text='Share with community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule-Based Strategy',
                'verbose_name_plural': 'Rule-Based Strategies',
                'db_table': 'strategies_rule_based',
            },
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('signal_direction', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=10, null=True)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=4, help_text='Expected price or percentage', max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, help_text='Price at which to exit (Stop Loss)', max_digits=15, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, help_text='Reference price when signal was generated', max_digits=15, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Actual close price on signal date', max_digits=15, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=4, help_text='Absolute profit/loss', max_digits=15, null=True)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage profit/loss', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('NEUTRAL', 'Neutral')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Signal',
                'verbose_name_plural': 'Strategy Signals',
                'db_table': 'strategies_signal',
            },
        ),
    ]
