# Generated by Django 5.1.4 on 2025-12-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPredefined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predefined Strategy',
                'verbose_name_plural': 'Predefined Strategies',
                'db_table': 'strategies_predefined',
            },
        ),
        migrations.CreateModel(
            name='StrategyRuleBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rules_json', models.JSONField(help_text='Strategy rules in JSON format')),
                ('is_public', models.BooleanField(default=False, help_text='Share with community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule-Based Strategy',
                'verbose_name_plural': 'Rule-Based Strategies',
                'db_table': 'strategies_rule_based',
            },
        ),
    ]
