# Generated by Django 5.1.4 on 2025-12-14 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategypredefined',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyrulebased',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
