# Generated by Django 6.0.2 on 2026-02-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('stocks', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockfinderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategymaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyrulebased',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to='adminpanel.adminuser'),
        ),
        migrations.AddField(
            model_name='strategyrulebased',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategymaster',
            name='rule_based_strategy',
            field=models.ForeignKey(blank=True, help_text='Linked rule-based strategy for AUTO type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyrulebased'),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_signals', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategies.strategymaster'),
        ),
        migrations.AddIndex(
            model_name='strategysignal',
            index=models.Index(fields=['stock', 'strategy', '-date'], name='strategies__stock_i_96479e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategysignal',
            unique_together={('stock', 'strategy', 'date')},
        ),
    ]
