# Generated by Django 5.1.4 on 2025-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0004_alter_backtestrun_strategy_predefined'),
        ('strategies', '0003_remove_strategypredefined_created_by_strategymaster_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrategyPredefined',
        ),
        migrations.AddIndex(
            model_name='strategysignal',
            index=models.Index(fields=['stock', 'strategy', '-date'], name='strategies__stock_i_96479e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategysignal',
            unique_together={('stock', 'strategy', 'date')},
        ),
    ]
