# Generated by Django 5.1.4 on 2025-12-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_delete_strategypredefined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategymaster',
            name='logic',
            field=models.TextField(blank=True, help_text='Strategy logic for AUTO type', null=True),
        ),
        migrations.AddField(
            model_name='strategymaster',
            name='type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=10),
        ),
    ]
