# Generated by Django 5.1.4 on 2025-12-28 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('strategies', '0005_strategymaster_logic_strategymaster_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrulebased',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to='adminpanel.adminuser'),
        ),
        migrations.AlterField(
            model_name='strategyrulebased',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
