# Generated by Django 5.1.4 on 2025-12-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_strategyrulebased_created_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategymaster',
            name='logic',
        ),
        migrations.AddField(
            model_name='strategymaster',
            name='rule_based_strategy',
            field=models.ForeignKey(blank=True, help_text='Linked rule-based strategy for AUTO type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyrulebased'),
        ),
    ]
