# Generated by Django 5.1.4 on 2025-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_remove_strategymaster_logic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategymaster',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
