# Generated by Django 5.1.4 on 2026-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_alter_strategymaster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategymaster',
            name='code',
            field=models.CharField(help_text='Unique code for the strategy (e.g., DAILY_CLOSE_MOMENTUM)', max_length=50, unique=True),
        ),
    ]
