# Generated by Django 5.1.4 on 2026-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_alter_strategymaster_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysignal',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price at which to exit (Stop Loss)', max_digits=15, null=True),
        ),
    ]
