# Generated by Django 5.1.4 on 2026-01-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0010_strategysignal_stop_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysignal',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Reference price when signal was generated', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Actual close price on signal date', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Absolute profit/loss', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='pnl_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage profit/loss', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('NEUTRAL', 'Neutral')], default='PENDING', max_length=10),
        ),
    ]
