# Generated by Django 5.1.4 on 2026-01-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0011_strategysignal_entry_price_strategysignal_exit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategies', models.JSONField(help_text='List of strategy details used')),
                ('filters', models.JSONField(help_text='Filters applied (Sector, Category, Date, Direction)')),
                ('results', models.JSONField(help_text='List of stocks found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Finder History',
                'verbose_name_plural': 'Stock Finder Histories',
                'db_table': 'stock_finder_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
