# Generated by Django 5.1.4 on 2026-02-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0012_stockfinderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('configuration', models.JSONField(help_text='Strategy logic (Legs, Entry, Exit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option Strategy',
                'verbose_name_plural': 'Option Strategies',
                'db_table': 'strategies_option',
            },
        ),
    ]
