# Generated by Django 5.1.4 on 2026-02-05 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0013_optionstrategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategy',
            name='is_system',
            field=models.BooleanField(default=False, help_text='If True, visible to all users (Created by Admin)'),
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
