# Generated by Django 6.0.2 on 2026-02-19 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher value = Higher tier')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('available_period', models.CharField(choices=[('monthly', 'Monthly Only'), ('yearly', 'Yearly Only'), ('both', 'Both Monthly & Yearly')], default='both', help_text='Restrict this plan to specific billing intervals.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='If true, this plan is assigned to new users.')),
                ('default_period_days', models.IntegerField(default=30, help_text='Duration in days if assigned as default.')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('applicable_periods', models.CharField(blank=True, help_text='Comma separated: monthly,yearly', max_length=100)),
                ('max_usage', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('used_count', models.IntegerField(default=0)),
                ('applicable_plan', models.ForeignKey(blank=True, help_text='Specific plan this coupon applies to. Leave blank for all plans.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
            ],
        ),
    ]
