# Generated by Django 5.1.4 on 2026-01-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='default_period_days',
            field=models.IntegerField(default=30, help_text='Duration in days if assigned as default.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If true, this plan is assigned to new users.'),
        ),
    ]
