# Generated by Django 5.1.4 on 2026-01-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_default_period_days_plan_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_plans',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_plan',
            field=models.ForeignKey(blank=True, help_text='Specific plan this coupon applies to. Leave blank for all plans.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan'),
        ),
    ]
