# Generated by Django 5.1.4 on 2026-01-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_coupon_applicable_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = Higher tier'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
