# Generated by Django 5.1.4 on 2026-01-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptionusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='available_period',
            field=models.CharField(choices=[('monthly', 'Monthly Only'), ('yearly', 'Yearly Only'), ('both', 'Both Monthly & Yearly')], default='both', help_text='Restrict this plan to specific billing intervals.', max_length=20),
        ),
    ]
